### PR TITLE
Fix django 1.8 issue #54

### PR DESCRIPTION
**Pull request by bubuntux**
Relevant info
https://code.djangoproject.com/ticket/21414

### CODE REVIEW

**Comment by oden65** [comment]
@bubuntux you forgot lines 15 and 27

**Comment by jonashagstedt** [comment]
I'm working on a separate branch to make it Django 1.8 compatible.
The serializer tools are not the only bother in all this, there are quite a few things that has changed.

I have included your changes but I won't merge the pull request as it's all going into another branch.

**Comment by oden65** [comment]
Is that the 0.4.2 ? We are developing against Django 1.8 and would like use / test your changes

**Comment by jonashagstedt** [comment]
Yes, it's 0.4.2
I've added tox for it and all tests are passing for Django 1.8, but I haven't tried it in an actual project yet.

**Pull request closed without merging**
