### PR TITLE
Changes for Django 1.9

### PR DESCRIPTION
**Pull request by viaregio**

### CODE REVIEW

**Comment by csalexwilliams** [comment]
@jonashagstedt Can you please accept this pull request?

**Comment by jonashagstedt** [comment]
If you resolve the merge conflicts I will.

**Comment by csalexwilliams** [comment]
@viaregio Did some searching. My best guess is that you didn't merge your old pull request into master before resolving the merge conflicts.

**Comment by viaregio** [comment]
OK, it seems the conflict is resolved.

**Comment by csalexwilliams** [comment]
@viaregio :+1: Thanks so much!

**Pull request merged**
