### PR TITLE
Django 1.8 related model changed to related.related_model

### PR DESCRIPTION
**Pull request by jlemaes**
Turns out there were more fixes needed, i only saw the reverse_fk because i was only using that one in my project.
 + added more test for the object map

### CODE REVIEW

**Comment by jonashagstedt** [comment]
That's absolutely fantastic! 
Good work!

I ran the tests and this happened though:

    tests/test_object_map.py:96: in test_get_object_map_for_fk
        self.assertEqual(m['child_type'], 'childmodel')
    E   AssertionError: 'parentmodel' != 'childmodel'
    E   - parentmodel
    E   + childmodel
    1 failed, 135 passed, 9 warnings in 2.04 seconds

If you run `tox` do they all pass for you?

**Comment by jlemaes** [comment]
whoops, they don't, sorry. It looks like my master branch is not up to date with my previous fix, which is why the tests crash.

**Comment by jonashagstedt** [comment]
Got to love testing.
Really nice of you to sort the test out and help making this Django 1.8 compatible.

**Comment by jlemaes** [comment]
Now they work.
No problem, glad i could help.

**Comment by jonashagstedt** [comment]
All tests passing! Top stuff.

**Pull request merged**
