### PR TITLE
Django 1.8 reverse foreignkey fix

### PR DESCRIPTION
**Pull request by jlemaes**

### CODE REVIEW

**Comment by jlemaes** [comment]
#81

**Comment by jonashagstedt** [comment]
I would be happy to merge this PR, but before I do, would you mind writing a test to confirm it (just so I can be sure that it doesn't break anything etc.)

**Comment by jlemaes** [comment]
It should be covered now :)

**Comment by jonashagstedt** [comment]
Smashing! And all tests are passing

**Pull request merged**
